### ISSUE TITLE
Continuous Up Input

### ISSUE THREAD

**Issue by TechJeeper** [ghlre/GHLtarUtility#1]
With a PS3 GH Live Dongle - When GHLtarUtility is running, after the device is paired, if you unpair the guitar from the dongle (after auto-shutdown timeout) - Something sends a continuous up-arrow input.  This goes away if I pair the guitar, if I unplug the dongle or if I close GHLtarUtility.

**Comment by InvoxiPlayGames** [comment]
This issue should be fixed by #2.
